# https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#common-application-properties
server:
  tomcat:
    basedir: ${user.dir}/temp

# SPRING
spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 30MB

  mvc:
    static-path-pattern: '/assets/**'
  resources:
    static-locations: 'classpath:/assets/'

  # ehcache
  cache:
    ehcache:
      config: 'classpath:/config/ehcache.xml'

  #json
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# LOGGING
logging:
  config: 'classpath:logback.xml'

# shiro
shiro:
  login-url: '/console/login'
  success-url: '/console'
  hash-algorithm: MD5
  hash-iterations: 2
  username-param: username
  password-param: password
  remember-me-param: rememberMe
  filter-chain:
    authc: /console/login,/authenticated
    anon: /,/console/logout,/unauthorized,/assets/**,/image/**
    user: /console/**


# 文件路径
upload:
  pic: file:./upload/pic/